"
visitor implementa el patron visitor
"
Class {
	#name : #Visitor,
	#superclass : #Object,
	#category : #'JuegoLaberinto-Visitor'
}

{ #category : #'as yet unclassified' }
Visitor >> visitarArmario:unArmario [
"no hacer nada / implementacion predeterminada / forzar a que las subclases lo implementen"
]

{ #category : #'as yet unclassified' }
Visitor >> visitarBomba:unaBomba [
"no hacer nada / implementacion predeterminada / forzar a que las subclases lo implementen"
]

{ #category : #'as yet unclassified' }
Visitor >> visitarHabitacion:unaHab [
"no hacer nada / implementacion predeterminada / forzar a que las subclases lo implementen"
]

{ #category : #'as yet unclassified' }
Visitor >> visitarPared:unaPared [
"no hacer nada / implementacion predeterminada / forzar a que las subclases lo implementen"
]

{ #category : #'as yet unclassified' }
Visitor >> visitarPuerta:unaPuerta [
"no hacer nada / implementacion predeterminada / forzar a que las subclases lo implementen"
]

{ #category : #'as yet unclassified' }
Visitor >> visitarTunel:unTunel [
"no hacer nada / implementacion predeterminada / forzar a que las subclases lo implementen"
]
